#!/bin/bash
echo Date: March 10
grep '05:00:00 AM' 0310* | awk '{print $1,$2,$5,$6}'
grep '08:00:00 AM' 0310* | awk '{print $1,$2,$5,$6}'
grep '02:00:00 PM' 0310* | awk '{print $1,$2,$5,$6}'
grep '08:00:00 PM' 0310* | awk '{print $1,$2,$5,$6}'
grep '11:00:00 PM' 0310* | awk '{print $1,$2,$5,$6}'

#!/bin/bash
echo Date: March 12
grep '05:00:00 AM' 0312* | awk '{print $1,$2,$5,$6}'
grep '08:00:00 AM' 0312* | awk '{print $1,$2,$5,$6}'
grep '02:00:00 PM' 0312* | awk '{print $1,$2,$5,$6}'
grep '08:00:00 PM' 0312* | awk '{print $1,$2,$5,$6}'
grep '11:00:00 PM' 0312* | awk '{print $1,$2,$5,$6}'

#!/bin/bash
echo Date: March 15
grep '05:00:00 AM' 0315* | awk '{print $1,$2,$5,$6}'
grep '08:00:00 AM' 0315* | awk '{print $1,$2,$5,$6}'
grep '02:00:00 PM' 0315* | awk '{print $1,$2,$5,$6}'
grep '08:00:00 PM' 0315* | awk '{print $1,$2,$5,$6}'
grep '11:00:00 PM' 0315* | awk '{print $1,$2,$5,$6}'
